CREATE TABLE trading_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(16) NOT NULL CHECK (status IN ('ACTIVE', 'BANKRUPT')),
    credential_hash VARCHAR(64) NOT NULL UNIQUE CHECK (length(credential_hash) = 64),
    credential_expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    last_financial_change_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE wallet (
    account_id BIGINT PRIMARY KEY REFERENCES trading_account(id),
    balance NUMERIC(38,18) NOT NULL,
    used_margin NUMERIC(38,18) NOT NULL CHECK (used_margin >= 0),
    reserved_margin NUMERIC(38,18) NOT NULL CHECK (reserved_margin >= 0),
    realized_pnl NUMERIC(38,18) NOT NULL
);

CREATE TABLE position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES trading_account(id),
    trading_symbol_id BIGINT NOT NULL REFERENCES trading_symbol(id),
    side VARCHAR(8) NOT NULL CHECK (side IN ('LONG', 'SHORT')),
    quantity NUMERIC(28,8) NOT NULL CHECK (quantity > 0),
    entry_price NUMERIC(38,18) NOT NULL CHECK (entry_price > 0),
    leverage INTEGER NOT NULL CHECK (leverage BETWEEN 1 AND 20),
    margin NUMERIC(38,18) NOT NULL CHECK (margin > 0),
    status VARCHAR(16) NOT NULL CHECK (status IN ('OPEN', 'CLOSED', 'LIQUIDATED')),
    realized_pnl NUMERIC(38,18) NOT NULL,
    exit_price NUMERIC(38,18),
    opened_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ,
    CONSTRAINT position_close_state CHECK (
        (status = 'OPEN' AND closed_at IS NULL AND exit_price IS NULL AND realized_pnl = 0)
        OR (status <> 'OPEN' AND closed_at IS NOT NULL AND exit_price IS NOT NULL AND exit_price > 0)
    )
);

CREATE INDEX position_account_open_idx ON position (account_id, id) WHERE status = 'OPEN';
