CREATE TABLE trading_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES trading_account(id),
    position_id BIGINT NOT NULL REFERENCES position(id),
    trading_symbol_id BIGINT NOT NULL REFERENCES trading_symbol(id),
    side VARCHAR(8) NOT NULL CHECK (side IN ('LONG','SHORT')),
    type VARCHAR(16) NOT NULL CONSTRAINT order_type_check CHECK (type = 'MARKET'),
    action VARCHAR(16) NOT NULL CONSTRAINT order_action_check CHECK (action IN ('OPEN','CLOSE')),
    status VARCHAR(16) NOT NULL CONSTRAINT order_status_check CHECK (status = 'FILLED'),
    quantity NUMERIC(28,8) NOT NULL CHECK (quantity > 0),
    leverage INTEGER NOT NULL CHECK (leverage BETWEEN 1 AND 20),
    filled_price NUMERIC(38,18) NOT NULL CHECK (filled_price > 0),
    idempotency_key VARCHAR(100) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT order_idempotency_unique UNIQUE (account_id, idempotency_key)
);
CREATE INDEX order_account_history_idx ON trading_order(account_id, id DESC);
CREATE UNIQUE INDEX order_open_position_unique ON trading_order(position_id) WHERE action = 'OPEN';
CREATE UNIQUE INDEX order_close_position_unique ON trading_order(position_id) WHERE action = 'CLOSE';

CREATE TABLE fill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES trading_order(id),
    price NUMERIC(38,18) NOT NULL CHECK (price > 0),
    quantity NUMERIC(28,8) NOT NULL CHECK (quantity > 0),
    price_event_time TIMESTAMPTZ NOT NULL,
    executed_at TIMESTAMPTZ NOT NULL,
    realized_pnl NUMERIC(38,18) NOT NULL
);

